name: flutter_at_mini
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.4 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  convert: ^3.0.1
  dio: ^4.0.1
  dio_http2_adapter: ^2.0.0
  http: ^0.13.4
  http_parser: ^4.0.0
